const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slime Shirt",
      category: "Shirts",
      image: "/images/p1.jpeg",
      price: 120,
      brand: "Nike",
      rating: 5,
      numReviews: 10,
      description: "high quality products",
      countInStock: 1,
    },
    {
      _id: "2",
      name: "Adidas Fit Shirts",
      category: "Shirts",
      image: "/images/p2.jpeg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality products",
      countInStock: 2,
    },
    {
      _id: "3",
      name: "Lacoste Free Shirt",
      category: "Shirts",
      image: "/images/p3.jpeg",
      price: 50,
      brand: "Nike",
      rating: 4.1,
      numReviews: 17,
      description: "high quality products",
      countInStock: 5,
    },
    {
      _id: "4",
      name: "Nike Slim Pant",
      category: "Shirts",
      image: "/images/p4.jpeg",
      price: 150,
      brand: "Nike",
      rating: 3.5,
      numReviews: 55,
      description: "high quality products",
      countInStock: 20,
    },
    {
      _id: "5uma Slim Pant",
      name: "Puma Slim Pant",
      category: "Shirts",
      image: "/images/p5.jpeg",
      price: 10,
      brand: "Nike",
      rating: 2.5,
      numReviews: 14,
      description: "high quality products",
      countInStock: 2,
    },
    {
      _id: "6",
      name: "Panda Slime Shirt",
      category: "Shirts",
      image: "/images/p6.jpeg",
      price: 12,
      brand: "Nike",
      rating: 3.5,
      numReviews: 20,
      description: "high quality products",
      countInStock: 0,
    },
  ],

  staticText: {
    womenText:
      "Refresh your daily rotation with our women’s clothing range. With the freshest styles available all in one place, you can expect everyday basics, like women's tops and skirts, as well as must-have knitwear and cozy loungewear for downtime days. Plans to go out? Our women's dresses line up mini, midi and maxi styles that were made for summer evenings, while our stylish jeans and pants offer something to flatter every silhouette.",
    menText:
      "Refresh your daily rotation with our men’s clothing range. With the freshest styles available all in one place, you can expect everyday basics, like men's tops and skirts, as well as must-have knitwear and cozy loungewear for downtime days. Plans to go out? Our women's dresses line up mini, midi and maxi styles that were made for summer evenings, while our stylish jeans and pants offer something to flatter every silhouette.",
  },
};

export default data;
